server:
  port: 8080
  servlet:
    context-path: /vx/ds

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  groovy:
    template:
      check-template-location: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

